// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: training/v1/training.proto

package trainingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExperimentManagerService_SubmitExperiment_FullMethodName    = "/training.v1.ExperimentManagerService/SubmitExperiment"
	ExperimentManagerService_GetExperimentStatus_FullMethodName = "/training.v1.ExperimentManagerService/GetExperimentStatus"
)

// ExperimentManagerServiceClient is the client API for ExperimentManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExperimentManagerServiceClient interface {
	SubmitExperiment(ctx context.Context, in *SubmitExperimentRequest, opts ...grpc.CallOption) (*SubmitExperimentResponse, error)
	GetExperimentStatus(ctx context.Context, in *GetExperimentStatusRequest, opts ...grpc.CallOption) (*GetExperimentStatusResponse, error)
}

type experimentManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExperimentManagerServiceClient(cc grpc.ClientConnInterface) ExperimentManagerServiceClient {
	return &experimentManagerServiceClient{cc}
}

func (c *experimentManagerServiceClient) SubmitExperiment(ctx context.Context, in *SubmitExperimentRequest, opts ...grpc.CallOption) (*SubmitExperimentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitExperimentResponse)
	err := c.cc.Invoke(ctx, ExperimentManagerService_SubmitExperiment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *experimentManagerServiceClient) GetExperimentStatus(ctx context.Context, in *GetExperimentStatusRequest, opts ...grpc.CallOption) (*GetExperimentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExperimentStatusResponse)
	err := c.cc.Invoke(ctx, ExperimentManagerService_GetExperimentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExperimentManagerServiceServer is the server API for ExperimentManagerService service.
// All implementations must embed UnimplementedExperimentManagerServiceServer
// for forward compatibility.
type ExperimentManagerServiceServer interface {
	SubmitExperiment(context.Context, *SubmitExperimentRequest) (*SubmitExperimentResponse, error)
	GetExperimentStatus(context.Context, *GetExperimentStatusRequest) (*GetExperimentStatusResponse, error)
	mustEmbedUnimplementedExperimentManagerServiceServer()
}

// UnimplementedExperimentManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExperimentManagerServiceServer struct{}

func (UnimplementedExperimentManagerServiceServer) SubmitExperiment(context.Context, *SubmitExperimentRequest) (*SubmitExperimentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitExperiment not implemented")
}
func (UnimplementedExperimentManagerServiceServer) GetExperimentStatus(context.Context, *GetExperimentStatusRequest) (*GetExperimentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExperimentStatus not implemented")
}
func (UnimplementedExperimentManagerServiceServer) mustEmbedUnimplementedExperimentManagerServiceServer() {
}
func (UnimplementedExperimentManagerServiceServer) testEmbeddedByValue() {}

// UnsafeExperimentManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExperimentManagerServiceServer will
// result in compilation errors.
type UnsafeExperimentManagerServiceServer interface {
	mustEmbedUnimplementedExperimentManagerServiceServer()
}

func RegisterExperimentManagerServiceServer(s grpc.ServiceRegistrar, srv ExperimentManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedExperimentManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExperimentManagerService_ServiceDesc, srv)
}

func _ExperimentManagerService_SubmitExperiment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitExperimentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperimentManagerServiceServer).SubmitExperiment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperimentManagerService_SubmitExperiment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperimentManagerServiceServer).SubmitExperiment(ctx, req.(*SubmitExperimentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExperimentManagerService_GetExperimentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExperimentManagerServiceServer).GetExperimentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExperimentManagerService_GetExperimentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExperimentManagerServiceServer).GetExperimentStatus(ctx, req.(*GetExperimentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExperimentManagerService_ServiceDesc is the grpc.ServiceDesc for ExperimentManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExperimentManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "training.v1.ExperimentManagerService",
	HandlerType: (*ExperimentManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitExperiment",
			Handler:    _ExperimentManagerService_SubmitExperiment_Handler,
		},
		{
			MethodName: "GetExperimentStatus",
			Handler:    _ExperimentManagerService_GetExperimentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "training/v1/training.proto",
}
