// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertLog = `-- name: InsertLog :exec
INSERT INTO experiment_logs (experiment_id, content)                             
VALUES ($1, $2)
`

type InsertLogParams struct {
	ExperimentID uuid.UUID `json:"experiment_id"`
	Content      string    `json:"content"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.Exec(ctx, insertLog, arg.ExperimentID, arg.Content)
	return err
}

const listLogs = `-- name: ListLogs :many
SELECT id, experiment_id, content, logged_at FROM experiment_logs                                                    
WHERE experiment_id = $1                                                         
ORDER BY logged_at ASC
`

func (q *Queries) ListLogs(ctx context.Context, experimentID uuid.UUID) ([]ExperimentLog, error) {
	rows, err := q.db.Query(ctx, listLogs, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExperimentLog{}
	for rows.Next() {
		var i ExperimentLog
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Content,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogsSince = `-- name: ListLogsSince :many
SELECT id, experiment_id, content, logged_at FROM experiment_logs                                                    
WHERE experiment_id = $1 AND id > $2                                             
ORDER BY id ASC
`

type ListLogsSinceParams struct {
	ExperimentID uuid.UUID `json:"experiment_id"`
	ID           int64     `json:"id"`
}

func (q *Queries) ListLogsSince(ctx context.Context, arg ListLogsSinceParams) ([]ExperimentLog, error) {
	rows, err := q.db.Query(ctx, listLogsSince, arg.ExperimentID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExperimentLog{}
	for rows.Next() {
		var i ExperimentLog
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Content,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
