// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertMetric = `-- name: InsertMetric :exec
INSERT INTO experiment_metrics (experiment_id, step, metric_name, metric_value)  
VALUES ($1, $2, $3, $4)
`

type InsertMetricParams struct {
	ExperimentID uuid.UUID `json:"experiment_id"`
	Step         int32     `json:"step"`
	MetricName   string    `json:"metric_name"`
	MetricValue  float64   `json:"metric_value"`
}

func (q *Queries) InsertMetric(ctx context.Context, arg InsertMetricParams) error {
	_, err := q.db.Exec(ctx, insertMetric,
		arg.ExperimentID,
		arg.Step,
		arg.MetricName,
		arg.MetricValue,
	)
	return err
}

const listMetricsByExperiment = `-- name: ListMetricsByExperiment :many
SELECT id, experiment_id, step, metric_name, metric_value, recorded_at FROM experiment_metrics                                                 
WHERE experiment_id = $1                                                         
ORDER BY step ASC
`

func (q *Queries) ListMetricsByExperiment(ctx context.Context, experimentID uuid.UUID) ([]ExperimentMetric, error) {
	rows, err := q.db.Query(ctx, listMetricsByExperiment, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExperimentMetric{}
	for rows.Next() {
		var i ExperimentMetric
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Step,
			&i.MetricName,
			&i.MetricValue,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetricsByName = `-- name: ListMetricsByName :many
SELECT id, experiment_id, step, metric_name, metric_value, recorded_at FROM experiment_metrics                                                 
WHERE experiment_id = $1 AND metric_name = $2                                    
ORDER BY step ASC
`

type ListMetricsByNameParams struct {
	ExperimentID uuid.UUID `json:"experiment_id"`
	MetricName   string    `json:"metric_name"`
}

func (q *Queries) ListMetricsByName(ctx context.Context, arg ListMetricsByNameParams) ([]ExperimentMetric, error) {
	rows, err := q.db.Query(ctx, listMetricsByName, arg.ExperimentID, arg.MetricName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExperimentMetric{}
	for rows.Next() {
		var i ExperimentMetric
		if err := rows.Scan(
			&i.ID,
			&i.ExperimentID,
			&i.Step,
			&i.MetricName,
			&i.MetricValue,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
