// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExperimentStatus string

const (
	ExperimentStatusCreated    ExperimentStatus = "created"
	ExperimentStatusQueued     ExperimentStatus = "queued"
	ExperimentStatusTraining   ExperimentStatus = "training"
	ExperimentStatusEvaluating ExperimentStatus = "evaluating"
	ExperimentStatusCompleted  ExperimentStatus = "completed"
	ExperimentStatusFailed     ExperimentStatus = "failed"
	ExperimentStatusCancelled  ExperimentStatus = "cancelled"
)

func (e *ExperimentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExperimentStatus(s)
	case string:
		*e = ExperimentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExperimentStatus: %T", src)
	}
	return nil
}

type NullExperimentStatus struct {
	ExperimentStatus ExperimentStatus `json:"experiment_status"`
	Valid            bool             `json:"valid"` // Valid is true if ExperimentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExperimentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExperimentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExperimentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExperimentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExperimentStatus), nil
}

type ModelStage string

const (
	ModelStageNone       ModelStage = "none"
	ModelStageStaging    ModelStage = "staging"
	ModelStageProduction ModelStage = "production"
	ModelStageArchived   ModelStage = "archived"
)

func (e *ModelStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelStage(s)
	case string:
		*e = ModelStage(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelStage: %T", src)
	}
	return nil
}

type NullModelStage struct {
	ModelStage ModelStage `json:"model_stage"`
	Valid      bool       `json:"valid"` // Valid is true if ModelStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelStage) Scan(value interface{}) error {
	if value == nil {
		ns.ModelStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelStage), nil
}

type ModelType string

const (
	ModelTypeBase        ModelType = "base"
	ModelTypeLoraAdapter ModelType = "lora_adapter"
	ModelTypeMerged      ModelType = "merged"
)

func (e *ModelType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelType(s)
	case string:
		*e = ModelType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelType: %T", src)
	}
	return nil
}

type NullModelType struct {
	ModelType ModelType `json:"model_type"`
	Valid     bool      `json:"valid"` // Valid is true if ModelType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelType) Scan(value interface{}) error {
	if value == nil {
		ns.ModelType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelType), nil
}

type AuditLog struct {
	ID         int64              `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Action     string             `json:"action"`
	Actor      string             `json:"actor"`
	Details    []byte             `json:"details"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Experiment struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Status         ExperimentStatus   `json:"status"`
	Config         []byte             `json:"config"`
	TaskqueueJobID pgtype.UUID        `json:"taskqueue_job_id"`
	WorkerID       pgtype.Text        `json:"worker_id"`
	GpuCount       int32              `json:"gpu_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type ExperimentLog struct {
	ID           int64              `json:"id"`
	ExperimentID uuid.UUID          `json:"experiment_id"`
	Content      string             `json:"content"`
	LoggedAt     pgtype.Timestamptz `json:"logged_at"`
}

type ExperimentMetric struct {
	ID           int64              `json:"id"`
	ExperimentID uuid.UUID          `json:"experiment_id"`
	Step         int32              `json:"step"`
	MetricName   string             `json:"metric_name"`
	MetricValue  float64            `json:"metric_value"`
	RecordedAt   pgtype.Timestamptz `json:"recorded_at"`
}

type Model struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Version            string             `json:"version"`
	Stage              ModelStage         `json:"stage"`
	ModelType          ModelType          `json:"model_type"`
	ArtifactUri        string             `json:"artifact_uri"`
	ParentBaseModelID  pgtype.UUID        `json:"parent_base_model_id"`
	ParentExperimentID pgtype.UUID        `json:"parent_experiment_id"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type ServingConfig struct {
	ID            int64              `json:"id"`
	ModelName     string             `json:"model_name"`
	TrafficSplits []byte             `json:"traffic_splits"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
