// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getModel = `-- name: GetModel :one
SELECT id, name, version, stage, model_type, artifact_uri, parent_base_model_id, parent_experiment_id, metadata, created_at FROM models WHERE id = $1
`

func (q *Queries) GetModel(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRow(ctx, getModel, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Stage,
		&i.ModelType,
		&i.ArtifactUri,
		&i.ParentBaseModelID,
		&i.ParentExperimentID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listModels = `-- name: ListModels :many
SELECT id, name, version, stage, model_type, artifact_uri, parent_base_model_id, parent_experiment_id, metadata, created_at FROM models                                                             
ORDER BY created_at DESC                                                         
LIMIT $1 OFFSET $2
`

type ListModelsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error) {
	rows, err := q.db.Query(ctx, listModels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Stage,
			&i.ModelType,
			&i.ArtifactUri,
			&i.ParentBaseModelID,
			&i.ParentExperimentID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerModel = `-- name: RegisterModel :one
INSERT INTO models (name, version, model_type, artifact_uri,                     
parent_base_model_id, parent_experiment_id, metadata)                            
VALUES ($1, $2, $3, $4, $5, $6, $7)                                              
RETURNING id, name, version, stage, model_type, artifact_uri, parent_base_model_id, parent_experiment_id, metadata, created_at
`

type RegisterModelParams struct {
	Name               string      `json:"name"`
	Version            string      `json:"version"`
	ModelType          ModelType   `json:"model_type"`
	ArtifactUri        string      `json:"artifact_uri"`
	ParentBaseModelID  pgtype.UUID `json:"parent_base_model_id"`
	ParentExperimentID pgtype.UUID `json:"parent_experiment_id"`
	Metadata           []byte      `json:"metadata"`
}

func (q *Queries) RegisterModel(ctx context.Context, arg RegisterModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, registerModel,
		arg.Name,
		arg.Version,
		arg.ModelType,
		arg.ArtifactUri,
		arg.ParentBaseModelID,
		arg.ParentExperimentID,
		arg.Metadata,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Stage,
		&i.ModelType,
		&i.ArtifactUri,
		&i.ParentBaseModelID,
		&i.ParentExperimentID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const updateModelStage = `-- name: UpdateModelStage :one
UPDATE models                                                                    
SET stage = $2                                                                   
WHERE id = $1                                         
RETURNING id, name, version, stage, model_type, artifact_uri, parent_base_model_id, parent_experiment_id, metadata, created_at
`

type UpdateModelStageParams struct {
	ID    uuid.UUID  `json:"id"`
	Stage ModelStage `json:"stage"`
}

func (q *Queries) UpdateModelStage(ctx context.Context, arg UpdateModelStageParams) (Model, error) {
	row := q.db.QueryRow(ctx, updateModelStage, arg.ID, arg.Stage)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Stage,
		&i.ModelType,
		&i.ArtifactUri,
		&i.ParentBaseModelID,
		&i.ParentExperimentID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
