// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: training.proto

package trainingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperimentID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentID) Reset() {
	*x = ExperimentID{}
	mi := &file_training_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentID) ProtoMessage() {}

func (x *ExperimentID) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentID.ProtoReflect.Descriptor instead.
func (*ExperimentID) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{0}
}

func (x *ExperimentID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FinetuneConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BaseModel     string                 `protobuf:"bytes,2,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	LoraConfig    *LoraConfig            `protobuf:"bytes,3,opt,name=lora_config,json=loraConfig,proto3" json:"lora_config,omitempty"`
	Dataset       *DatasetRef            `protobuf:"bytes,4,opt,name=dataset,proto3" json:"dataset,omitempty"`
	TrainingArgs  *TrainingArgs          `protobuf:"bytes,5,opt,name=training_args,json=trainingArgs,proto3" json:"training_args,omitempty"`
	Resources     *ResourceRequirements  `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinetuneConfig) Reset() {
	*x = FinetuneConfig{}
	mi := &file_training_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinetuneConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinetuneConfig) ProtoMessage() {}

func (x *FinetuneConfig) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinetuneConfig.ProtoReflect.Descriptor instead.
func (*FinetuneConfig) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{1}
}

func (x *FinetuneConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FinetuneConfig) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *FinetuneConfig) GetLoraConfig() *LoraConfig {
	if x != nil {
		return x.LoraConfig
	}
	return nil
}

func (x *FinetuneConfig) GetDataset() *DatasetRef {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *FinetuneConfig) GetTrainingArgs() *TrainingArgs {
	if x != nil {
		return x.TrainingArgs
	}
	return nil
}

func (x *FinetuneConfig) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

type LoraConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Alpha         float32                `protobuf:"fixed32,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	TargetModules []string               `protobuf:"bytes,3,rep,name=target_modules,json=targetModules,proto3" json:"target_modules,omitempty"`
	Dropout       float32                `protobuf:"fixed32,4,opt,name=dropout,proto3" json:"dropout,omitempty"`
	TaskType      string                 `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoraConfig) Reset() {
	*x = LoraConfig{}
	mi := &file_training_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoraConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoraConfig) ProtoMessage() {}

func (x *LoraConfig) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoraConfig.ProtoReflect.Descriptor instead.
func (*LoraConfig) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{2}
}

func (x *LoraConfig) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LoraConfig) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *LoraConfig) GetTargetModules() []string {
	if x != nil {
		return x.TargetModules
	}
	return nil
}

func (x *LoraConfig) GetDropout() float32 {
	if x != nil {
		return x.Dropout
	}
	return 0
}

func (x *LoraConfig) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type DatasetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Split         string                 `protobuf:"bytes,3,opt,name=split,proto3" json:"split,omitempty"`
	MaxSamples    int32                  `protobuf:"varint,4,opt,name=max_samples,json=maxSamples,proto3" json:"max_samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetRef) Reset() {
	*x = DatasetRef{}
	mi := &file_training_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetRef) ProtoMessage() {}

func (x *DatasetRef) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetRef.ProtoReflect.Descriptor instead.
func (*DatasetRef) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{3}
}

func (x *DatasetRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetRef) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DatasetRef) GetSplit() string {
	if x != nil {
		return x.Split
	}
	return ""
}

func (x *DatasetRef) GetMaxSamples() int32 {
	if x != nil {
		return x.MaxSamples
	}
	return 0
}

type TrainingArgs struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	NumTrainEpochs            int32                  `protobuf:"varint,1,opt,name=num_train_epochs,json=numTrainEpochs,proto3" json:"num_train_epochs,omitempty"`
	PerDeviceTrainBatchSize   int32                  `protobuf:"varint,2,opt,name=per_device_train_batch_size,json=perDeviceTrainBatchSize,proto3" json:"per_device_train_batch_size,omitempty"`
	GradientAccumulationSteps int32                  `protobuf:"varint,3,opt,name=gradient_accumulation_steps,json=gradientAccumulationSteps,proto3" json:"gradient_accumulation_steps,omitempty"`
	LearningRate              float32                `protobuf:"fixed32,4,opt,name=learning_rate,json=learningRate,proto3" json:"learning_rate,omitempty"`
	LrSchedulerType           string                 `protobuf:"bytes,5,opt,name=lr_scheduler_type,json=lrSchedulerType,proto3" json:"lr_scheduler_type,omitempty"`
	WarmupRatio               float32                `protobuf:"fixed32,6,opt,name=warmup_ratio,json=warmupRatio,proto3" json:"warmup_ratio,omitempty"`
	UseFp16                   bool                   `protobuf:"varint,7,opt,name=use_fp16,json=useFp16,proto3" json:"use_fp16,omitempty"`
	MaxSeqLength              int32                  `protobuf:"varint,8,opt,name=max_seq_length,json=maxSeqLength,proto3" json:"max_seq_length,omitempty"`
	LoggingSteps              int32                  `protobuf:"varint,9,opt,name=logging_steps,json=loggingSteps,proto3" json:"logging_steps,omitempty"`
	SaveSteps                 int32                  `protobuf:"varint,10,opt,name=save_steps,json=saveSteps,proto3" json:"save_steps,omitempty"`
	EvalSteps                 int32                  `protobuf:"varint,11,opt,name=eval_steps,json=evalSteps,proto3" json:"eval_steps,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *TrainingArgs) Reset() {
	*x = TrainingArgs{}
	mi := &file_training_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingArgs) ProtoMessage() {}

func (x *TrainingArgs) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingArgs.ProtoReflect.Descriptor instead.
func (*TrainingArgs) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{4}
}

func (x *TrainingArgs) GetNumTrainEpochs() int32 {
	if x != nil {
		return x.NumTrainEpochs
	}
	return 0
}

func (x *TrainingArgs) GetPerDeviceTrainBatchSize() int32 {
	if x != nil {
		return x.PerDeviceTrainBatchSize
	}
	return 0
}

func (x *TrainingArgs) GetGradientAccumulationSteps() int32 {
	if x != nil {
		return x.GradientAccumulationSteps
	}
	return 0
}

func (x *TrainingArgs) GetLearningRate() float32 {
	if x != nil {
		return x.LearningRate
	}
	return 0
}

func (x *TrainingArgs) GetLrSchedulerType() string {
	if x != nil {
		return x.LrSchedulerType
	}
	return ""
}

func (x *TrainingArgs) GetWarmupRatio() float32 {
	if x != nil {
		return x.WarmupRatio
	}
	return 0
}

func (x *TrainingArgs) GetUseFp16() bool {
	if x != nil {
		return x.UseFp16
	}
	return false
}

func (x *TrainingArgs) GetMaxSeqLength() int32 {
	if x != nil {
		return x.MaxSeqLength
	}
	return 0
}

func (x *TrainingArgs) GetLoggingSteps() int32 {
	if x != nil {
		return x.LoggingSteps
	}
	return 0
}

func (x *TrainingArgs) GetSaveSteps() int32 {
	if x != nil {
		return x.SaveSteps
	}
	return 0
}

func (x *TrainingArgs) GetEvalSteps() int32 {
	if x != nil {
		return x.EvalSteps
	}
	return 0
}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GpuCount      int32                  `protobuf:"varint,1,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuType       string                 `protobuf:"bytes,2,opt,name=gpu_type,json=gpuType,proto3" json:"gpu_type,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,4,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_training_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceRequirements) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *ResourceRequirements) GetGpuType() string {
	if x != nil {
		return x.GpuType
	}
	return ""
}

func (x *ResourceRequirements) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ResourceRequirements) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type ExperimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentResponse) Reset() {
	*x = ExperimentResponse{}
	mi := &file_training_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentResponse) ProtoMessage() {}

func (x *ExperimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentResponse.ProtoReflect.Descriptor instead.
func (*ExperimentResponse) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{6}
}

func (x *ExperimentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExperimentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExperimentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ExperimentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BaseModel     string                 `protobuf:"bytes,4,opt,name=base_model,json=baseModel,proto3" json:"base_model,omitempty"`
	CurrentStep   int32                  `protobuf:"varint,5,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,6,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentStatus) Reset() {
	*x = ExperimentStatus{}
	mi := &file_training_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentStatus) ProtoMessage() {}

func (x *ExperimentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_training_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentStatus.ProtoReflect.Descriptor instead.
func (*ExperimentStatus) Descriptor() ([]byte, []int) {
	return file_training_proto_rawDescGZIP(), []int{7}
}

func (x *ExperimentStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExperimentStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExperimentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExperimentStatus) GetBaseModel() string {
	if x != nil {
		return x.BaseModel
	}
	return ""
}

func (x *ExperimentStatus) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *ExperimentStatus) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ExperimentStatus) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExperimentStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExperimentStatus) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

var File_training_proto protoreflect.FileDescriptor

const file_training_proto_rawDesc = "" +
	"\n" +
	"\x0etraining.proto\x12\x16mlplatform.training.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1e\n" +
	"\fExperimentID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdd\x02\n" +
	"\x0eFinetuneConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"base_model\x18\x02 \x01(\tR\tbaseModel\x12C\n" +
	"\vlora_config\x18\x03 \x01(\v2\".mlplatform.training.v1.LoraConfigR\n" +
	"loraConfig\x12<\n" +
	"\adataset\x18\x04 \x01(\v2\".mlplatform.training.v1.DatasetRefR\adataset\x12I\n" +
	"\rtraining_args\x18\x05 \x01(\v2$.mlplatform.training.v1.TrainingArgsR\ftrainingArgs\x12J\n" +
	"\tresources\x18\x06 \x01(\v2,.mlplatform.training.v1.ResourceRequirementsR\tresources\"\x94\x01\n" +
	"\n" +
	"LoraConfig\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x14\n" +
	"\x05alpha\x18\x02 \x01(\x02R\x05alpha\x12%\n" +
	"\x0etarget_modules\x18\x03 \x03(\tR\rtargetModules\x12\x18\n" +
	"\adropout\x18\x04 \x01(\x02R\adropout\x12\x1b\n" +
	"\ttask_type\x18\x05 \x01(\tR\btaskType\"q\n" +
	"\n" +
	"DatasetRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05split\x18\x03 \x01(\tR\x05split\x12\x1f\n" +
	"\vmax_samples\x18\x04 \x01(\x05R\n" +
	"maxSamples\"\xce\x03\n" +
	"\fTrainingArgs\x12(\n" +
	"\x10num_train_epochs\x18\x01 \x01(\x05R\x0enumTrainEpochs\x12<\n" +
	"\x1bper_device_train_batch_size\x18\x02 \x01(\x05R\x17perDeviceTrainBatchSize\x12>\n" +
	"\x1bgradient_accumulation_steps\x18\x03 \x01(\x05R\x19gradientAccumulationSteps\x12#\n" +
	"\rlearning_rate\x18\x04 \x01(\x02R\flearningRate\x12*\n" +
	"\x11lr_scheduler_type\x18\x05 \x01(\tR\x0flrSchedulerType\x12!\n" +
	"\fwarmup_ratio\x18\x06 \x01(\x02R\vwarmupRatio\x12\x19\n" +
	"\buse_fp16\x18\a \x01(\bR\auseFp16\x12$\n" +
	"\x0emax_seq_length\x18\b \x01(\x05R\fmaxSeqLength\x12#\n" +
	"\rlogging_steps\x18\t \x01(\x05R\floggingSteps\x12\x1d\n" +
	"\n" +
	"save_steps\x18\n" +
	" \x01(\x05R\tsaveSteps\x12\x1d\n" +
	"\n" +
	"eval_steps\x18\v \x01(\x05R\tevalSteps\"\x8b\x01\n" +
	"\x14ResourceRequirements\x12\x1b\n" +
	"\tgpu_count\x18\x01 \x01(\x05R\bgpuCount\x12\x19\n" +
	"\bgpu_type\x18\x02 \x01(\tR\agpuType\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vtimeout_sec\x18\x04 \x01(\x05R\n" +
	"timeoutSec\"w\n" +
	"\x12ExperimentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe6\x02\n" +
	"\x10ExperimentStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"base_model\x18\x04 \x01(\tR\tbaseModel\x12!\n" +
	"\fcurrent_step\x18\x05 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x06 \x01(\x05R\n" +
	"totalSteps\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt2\xe2\x01\n" +
	"\x11ExperimentManager\x12f\n" +
	"\x10SubmitExperiment\x12&.mlplatform.training.v1.FinetuneConfig\x1a*.mlplatform.training.v1.ExperimentResponse\x12e\n" +
	"\x13GetExperimentStatus\x12$.mlplatform.training.v1.ExperimentID\x1a(.mlplatform.training.v1.ExperimentStatusBNZLgithub.com/tradaokamsa/ml-platform/go-control-plane/internal/grpc/trainingv1b\x06proto3"

var (
	file_training_proto_rawDescOnce sync.Once
	file_training_proto_rawDescData []byte
)

func file_training_proto_rawDescGZIP() []byte {
	file_training_proto_rawDescOnce.Do(func() {
		file_training_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)))
	})
	return file_training_proto_rawDescData
}

var file_training_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_training_proto_goTypes = []any{
	(*ExperimentID)(nil),          // 0: mlplatform.training.v1.ExperimentID
	(*FinetuneConfig)(nil),        // 1: mlplatform.training.v1.FinetuneConfig
	(*LoraConfig)(nil),            // 2: mlplatform.training.v1.LoraConfig
	(*DatasetRef)(nil),            // 3: mlplatform.training.v1.DatasetRef
	(*TrainingArgs)(nil),          // 4: mlplatform.training.v1.TrainingArgs
	(*ResourceRequirements)(nil),  // 5: mlplatform.training.v1.ResourceRequirements
	(*ExperimentResponse)(nil),    // 6: mlplatform.training.v1.ExperimentResponse
	(*ExperimentStatus)(nil),      // 7: mlplatform.training.v1.ExperimentStatus
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_training_proto_depIdxs = []int32{
	2,  // 0: mlplatform.training.v1.FinetuneConfig.lora_config:type_name -> mlplatform.training.v1.LoraConfig
	3,  // 1: mlplatform.training.v1.FinetuneConfig.dataset:type_name -> mlplatform.training.v1.DatasetRef
	4,  // 2: mlplatform.training.v1.FinetuneConfig.training_args:type_name -> mlplatform.training.v1.TrainingArgs
	5,  // 3: mlplatform.training.v1.FinetuneConfig.resources:type_name -> mlplatform.training.v1.ResourceRequirements
	8,  // 4: mlplatform.training.v1.ExperimentResponse.created_at:type_name -> google.protobuf.Timestamp
	8,  // 5: mlplatform.training.v1.ExperimentStatus.created_at:type_name -> google.protobuf.Timestamp
	8,  // 6: mlplatform.training.v1.ExperimentStatus.started_at:type_name -> google.protobuf.Timestamp
	8,  // 7: mlplatform.training.v1.ExperimentStatus.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 8: mlplatform.training.v1.ExperimentManager.SubmitExperiment:input_type -> mlplatform.training.v1.FinetuneConfig
	0,  // 9: mlplatform.training.v1.ExperimentManager.GetExperimentStatus:input_type -> mlplatform.training.v1.ExperimentID
	6,  // 10: mlplatform.training.v1.ExperimentManager.SubmitExperiment:output_type -> mlplatform.training.v1.ExperimentResponse
	7,  // 11: mlplatform.training.v1.ExperimentManager.GetExperimentStatus:output_type -> mlplatform.training.v1.ExperimentStatus
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_training_proto_init() }
func file_training_proto_init() {
	if File_training_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_proto_rawDesc), len(file_training_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_training_proto_goTypes,
		DependencyIndexes: file_training_proto_depIdxs,
		MessageInfos:      file_training_proto_msgTypes,
	}.Build()
	File_training_proto = out.File
	file_training_proto_goTypes = nil
	file_training_proto_depIdxs = nil
}
