name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:                                                                                                              
  lint-proto:                                                                                                      
    runs-on: ubuntu-latest                                                                                         
    steps:                                                                                                         
      - uses: actions/checkout@v4                                                                                  
      - uses: bufbuild/buf-setup-action@v1                                                                         
      - run: buf dep update && buf lint                                                                            
                                                                                                                    
  build-go:                                                                                                        
    runs-on: ubuntu-latest                                                                                         
    needs: [lint-proto]                                                                                            
    steps:                                                                                                         
      - uses: actions/checkout@v4                                                                                  
      - uses: actions/setup-go@v5                                                                                  
        with:                                                                                                      
          go-version: "1.22"                                                                                       
      - uses: bufbuild/buf-setup-action@v1                                                                         
      - run: buf dep update && buf generate                                                                        
      - run: cd go-control-plane && go build ./...                                                                 
      - run: cd go-control-plane && go test -race ./...